project_id = "qoolzhzdcfnyblymdvbq"

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send-message]
verify_jwt = false

[functions.zapi-sync-contacts]
verify_jwt = true

[functions.zapi-send-file]
verify_jwt = false

[functions.zapi-sync-history]
verify_jwt = false

[functions.create-agent]
verify_jwt = false

[functions.ai-generate-reply]
verify_jwt = false

[functions.ai-maybe-reply]
verify_jwt = false

[functions.ai-test]
verify_jwt = false

[functions.kb-generate-embedding]
verify_jwt = true

[functions.kb-daily-ingest]
verify_jwt = true

[functions.notify-open-tickets-group]
verify_jwt = true

[functions.zapi-fix-group-duplicates]
verify_jwt = true

[functions.protocol-opened]
verify_jwt = false

[functions.protocol-client]
verify_jwt = false

[functions.group-resolution-handler]
verify_jwt = false

[functions.assign-conversation]
verify_jwt = false

[functions.mark-conversation-read]
verify_jwt = false

[functions.ai-auto-reactivate]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.create-protocol]
verify_jwt = false

[functions.create-ticket]
verify_jwt = false

[functions.create-task]
verify_jwt = false

[functions.rebuild-plan]
verify_jwt = false

[functions.fix-db-schema]
enabled = true
verify_jwt = true
import_map = "./functions/fix-db-schema/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fix-db-schema/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fix-db-schema/*.html" ]
