project_id = "mifoqjuhwljudovtuoka"

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send-message]
verify_jwt = true

[functions.zapi-sync-contacts]
verify_jwt = true

[functions.zapi-send-file]
verify_jwt = true

[functions.zapi-sync-history]
verify_jwt = true
